name: Go

on:
  push:
    branches: "**"
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: "**"
    paths-ignore:
      - "docs/**"

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Cover
        run: go test -race -coverprofile="coverage.out" -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
